;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        helm-M-x
        indent-for-tab-command
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        helm-confirm-and-exit-minibuffer
        ))
